"""
Configuration for Crypto Signal System v3.
All settings centralized here. Secrets loaded from secrets.py.
"""

# DEPLOYMENT MODE: fixture, historical_replay, paper, testnet
MODE = "testnet"

# DATA PATHS
DATA_DIR = "data"
LOGS_DIR = "logs"
STATE_DIR = "state"

# COLLECTION & ANALYSIS INTERVALS (seconds)
COLLECTOR_INTERVAL = 300  # 5 minutes
VOLUME_SCAN_INTERVAL = 45  # 30-60 seconds
EXIT_WATCH_INTERVAL = 10  # continuous exit monitor

# TRACKED COINS (symbols for multi-exchange use)
TRACKED_COINS = ["BTC", "ETH", "XRP", "ADA", "SOL"]

# ANALYST CONFIGURATION
ANALYSTS_ENABLED = {
    "technical": True,
    "volume": True,
    "order_book": True,
    "on_chain": True,
    "sentiment": True,
}

# SENTIMENT LLM (Ollama local)
SENTIMENT_MODEL = "llama2"
SENTIMENT_TIMEOUT_SEC = 30
SENTIMENT_MAX_RETRIES = 2

# CEO DECISION LLM
CEO_MODEL = "llama2"
CEO_TIMEOUT_SEC = 30
CEO_MAX_RETRIES = 2

# BULL/BEAR RESEARCHERS LLM
RESEARCHER_TIMEOUT_SEC = 30
RESEARCHER_MAX_RETRIES = 2

# EDGE VALIDATION: minimum sample size and p-value threshold
MIN_SAMPLE_SIZE_PER_COIN = 20
MIN_SAMPLE_SIZE_REGIME = 15
EDGE_P_VALUE_THRESHOLD = 0.05
OUT_OF_SAMPLE_RATIO = 0.2  # 80% train, 20% test

# REGIME DETECTION
REGIME_WINDOW_HOURS = 24
REGIME_VOLATILITY_THRESHOLD_PERCENT = 3

# TECHNICAL INDICATORS
RSI_PERIOD = 14
RSI_OVERBOUGHT = 70
RSI_OVERSOLD = 30
MACD_FAST = 12
MACD_SLOW = 26
MACD_SIGNAL = 9
EMA_SHORT = 20
EMA_LONG = 50
BB_PERIOD = 20
BB_STDDEV = 2
ATR_PERIOD = 14

# VOLUME ANALYSIS
VOLUME_BREAKOUT_THRESHOLD = 1.5  # 150% of average

# ORDER BOOK ANALYSIS
OB_IMBALANCE_THRESHOLD = 1.3  # 30% difference between buy/sell
OB_SPREAD_PERCENT_THRESHOLD = 0.1  # 0.1% spread triggers confidence reduction

# DECISION THRESHOLDS
BIG_TRADE_THRESHOLD_USD = 1000  # trades > $1000 need Telegram approval
ROUTINE_SIGNAL_CONFIDENCE_MIN = 0.6
STRONG_SIGNAL_CONFIDENCE_MIN = 0.75

# REGIME FILTER - stand down if regime unsuitable
REGIME_FILTER_ENABLED = True
REGIME_FILTER_STRICT = False  # if True, only trade in trending regime

# RISK MANAGEMENT
POSITION_SIZE_USD = 100
MAX_EXPOSURE_USD = 500  # max concurrent open trades USD
LEVERAGE = 1  # no leverage in testnet
ALLOW_SHORTS = False  # Binance Spot Testnet cannot open short positions
STOP_LOSS_PERCENT = 2.0
TAKE_PROFIT_TARGET_1_PERCENT = 5.0
TAKE_PROFIT_TARGET_2_PERCENT = 10.0
TAKE_PROFIT_TARGET_3_PERCENT = 15.0
TRAILING_STOP_PERCENT = 3.0
MAX_HOLD_TIME_HOURS = 48

# FEE ASSUMPTIONS for backtesting
MAKER_FEE_PERCENT = 0.1
TAKER_FEE_PERCENT = 0.1
SLIPPAGE_PERCENT = 0.05

# BINANCE TESTNET
BINANCE_TESTNET_BASE_URL = "https://testnet.binance.vision"
BINANCE_MARKET_DATA_BASE_URL = "https://api.binance.com"  # public live market data
BINANCE_SPOT_SYMBOL_FORMAT = "{}USDT"  # BTC -> BTCUSDT

# NOTIFICATIONS & APPROVALS
TELEGRAM_ENABLED = True
TELEGRAM_APPROVAL_TIMEOUT_SEC = 300  # 5 minutes to approve
TELEGRAM_NONCE_REUSE_PREVENTION = True
APPROVAL_CHAT_ID_ONLY = True  # only respond to configured chat

# WATCHDOG
WATCHDOG_ENABLED = True
WATCHDOG_CHECK_INTERVAL_SEC = 60
WATCHDOG_RESTART_RETRY_LIMIT = 3

# HEARTBEAT
HEARTBEAT_ENABLED = True
HEARTBEAT_INTERVAL_SEC = 300  # 5 minutes
HEARTBEAT_NOTIFICATION_THRESHOLD_SEC = 900  # alert if silent > 15 min

# DASHBOARD
DASHBOARD_ENABLED = True
DASHBOARD_HOST = "localhost"
DASHBOARD_PORT = 8000
DASHBOARD_AUTH_ENABLED = False  # localhost is assumed safe
DASHBOARD_LAN_MODE = False  # if True, requires auth + README acknowledgement

# KILL SWITCH
KILL_SWITCH_PATH = "state/kill_switch.lock"

# REFLECTION & LEARNING
REFLECTION_ENABLED = True
REFLECTION_MIN_SAMPLE_SIZE = 10
REFLECTION_CONFIDENCE_THRESHOLD = 0.7
REFLECTION_PROVISIONAL_LEARNING_ENABLED = True

# LOGGING
LOG_LEVEL = "INFO"  # DEBUG, INFO, WARNING, ERROR
LOG_FORMAT = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
LOG_FILE_MAX_BYTES = 10_000_000  # 10 MB
LOG_FILE_BACKUP_COUNT = 5

# ATOMIC WRITES
ATOMIC_WRITE_ENABLED = True
ATOMIC_WRITE_FSYNC = True

# RECONCILIATION
STATE_RECONCILIATION_ON_STARTUP = True
STATE_RECONCILIATION_INTERVAL_SEC = 3600  # 1 hour

# TAX LEDGER
TAX_LEDGER_CURRENCY = "GBP"
TAX_LEDGER_RETAIN_FILLS = True
